server:
  port: 8085
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
hm:
  db:
    host: 192.168.153.128
    pw: 123
    database: hm-cart
    username: root
  swagger:
    project: com.hmall.trade.controller

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
