server:
  port: 8081
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true
hm:
  db:
    host: 192.168.200.130
    pw: 123
    database: hm-item
    username: root
  swagger:
    project: com.hmall.item.controller

# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123
